### 1. Importa el paquete NUMPY bajo el nombre np.

In [2]:
import numpy as np

### 2. Imprime la versión de NUMPY y la configuración.

In [16]:
#help(np)

### 3. Genera un array tridimensional de 2x3x5 con valores aleatorios. Asigna el array a la variable "a"
 Desafío: hay al menos tres maneras fáciles que usan numpy para generar arrays aleatorios. ¿Cuántas formas puedes encontrar?

In [35]:
a= np.random.rand(2,3,5)


### 4. Imprime a.

In [36]:
print(a)

[[[0.63094687 0.13505544 0.68296679 0.29015483 0.15688465]
  [0.56614047 0.73167033 0.08152166 0.80222838 0.61659519]
  [0.24695999 0.64544205 0.49940335 0.80587994 0.81182963]]

 [[0.06002531 0.65935888 0.2135349  0.1915186  0.26007632]
  [0.48191053 0.47398217 0.77859578 0.33227326 0.19229132]
  [0.29819299 0.64953794 0.39487346 0.47767369 0.60343909]]]


### 5. Crea un array tridimensional de 5x2x3 con todos los valores igual a 1.
Asigna el array a la variable "b"

In [37]:
b= np.ones((5,2,3))

### 6. Imprime b.

In [38]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


### 7. ¿Tienen a y b el mismo tamaño? ¿Cómo lo demuestras en código Python?

In [39]:
a.shape == b.shape

print(a.shape, b.shape)

(2, 3, 5) (5, 2, 3)


### 8. ¿Es posible sumar a y b? ¿Por qué sí o por qué no?

No es posible debido al diferente tamaño/estructura de cada matriz

### 9. Transpone b para que tenga la misma estructura que a (es decir, se convierta en un array de 2x3x5). Asigna el array transpuesto a la variable "c".


In [40]:
c = np.transpose(b, (1,2,0))

### 10. Intenta sumar a y c. Ahora debería funcionar. Asigna la suma a la variable "d". Pero, ¿por qué funciona ahora?

In [41]:
d= a + c

### 11. Imprime a y d. ¿Notas la diferencia y la relación entre los dos arrays en términos de los valores? Explica.

In [42]:
print(d)

[[[1.63094687 1.13505544 1.68296679 1.29015483 1.15688465]
  [1.56614047 1.73167033 1.08152166 1.80222838 1.61659519]
  [1.24695999 1.64544205 1.49940335 1.80587994 1.81182963]]

 [[1.06002531 1.65935888 1.2135349  1.1915186  1.26007632]
  [1.48191053 1.47398217 1.77859578 1.33227326 1.19229132]
  [1.29819299 1.64953794 1.39487346 1.47767369 1.60343909]]]


### 12. Multiplica a y c. Asigna el resultado a e.

In [43]:
e= a * c

### 13. ¿Es e igual a a? ¿Por qué sí o por qué no?

In [48]:
False in (e == a)

# Estamos operando a con su identidad

False

### 14. Identifica los valores máximos, mínimos y medios en d. Asigna esos valores a las variables "d_max", "d_min" y "d_mean"


In [54]:
d_max= d.max()
d_min= d.min()
d_mean = d.mean()


### 15. Ahora queremos etiquetar los valores en d. Primero crea un array vacío "f" con la misma forma (es decir, 2x3x5) que d usando `np.empty`.


In [57]:
f = np.empty((2,3,5))

### 16. Rellena los valores en f. Para cada valor en d, si es mayor que d_min pero menor que d_mean, asigna 25 al valor correspondiente en f.
- Si un valor en d es mayor que d_mean pero menor que d_max, asigna 75 al valor correspondiente en f.
- Si un valor es igual a d_mean, asigna 50 al valor correspondiente en f.
- Asigna 0 al valor correspondiente(s) en f para d_min en d.
- Asigna 100 al valor correspondiente(s) en f para d_max en d.
- Al final, f debería tener solo los siguientes valores: 0, 25, 50, 75 y 100.


In [68]:
f[(d> d_mean)&(d<d_max)]= 75
f[(d< d_mean)&(d>d_min)]= 25
f[d == d_max]= 100
f[d == d_min]= 0
f

array([[[ 75.,  25.,  75.,  25.,  25.],
        [ 75.,  75.,  25.,  75.,  75.],
        [ 25.,  75.,  75.,  75., 100.]],

       [[  0.,  75.,  25.,  25.,  25.],
        [ 75.,  75.,  75.,  25.,  25.],
        [ 25.,  75.,  25.,  75.,  75.]]])

### 17. Imprime d y f. ¿Tienes el f esperado?
Por ejemplo, si tu d es: 
```python
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
```

Tu f debería ser:
```python
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],
       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
```

In [69]:
print(d,f)

[[[1.63094687 1.13505544 1.68296679 1.29015483 1.15688465]
  [1.56614047 1.73167033 1.08152166 1.80222838 1.61659519]
  [1.24695999 1.64544205 1.49940335 1.80587994 1.81182963]]

 [[1.06002531 1.65935888 1.2135349  1.1915186  1.26007632]
  [1.48191053 1.47398217 1.77859578 1.33227326 1.19229132]
  [1.29819299 1.64953794 1.39487346 1.47767369 1.60343909]]] [[[ 75.  25.  75.  25.  25.]
  [ 75.  75.  25.  75.  75.]
  [ 25.  75.  75.  75. 100.]]

 [[  0.  75.  25.  25.  25.]
  [ 75.  75.  75.  25.  25.]
  [ 25.  75.  25.  75.  75.]]]


### 18. Pregunta de bonificación: en lugar de usar números (es decir, 0, 25, 50, 75 y 100), ¿cómo usar valores de cadena  ("A", "B", "C", "D" y "E") para etiquetar los elementos del array? Esperas el resultado sea:

```python
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],
       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
```


In [122]:
etiquetas = [[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],
       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]]

etiquetas = np.array(etiquetas)
output_et= np.zeros(etiquetas.shape)

dictionary = {'A': 0 , 'B':25 , 'C':50 , 'D':75, 'E':100}

for element in dictionary:

    output_et[ np.where(etiquetas == element)  ] = dictionary[element]


print(output_et)


[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]
