# Instrucciones para Resolver Sistemas Ax=b y By=b

Se te proporciona una serie de tablas en la cual la última columna corresponde a un elemento conocido como **etiqueta**, y el resto de columnas se conoce como **características**. Tu tarea es llevar a cabo los siguientes pasos **sin el uso de funciones definidas (`def`)**, para que te familiarices con lo que sucede detrás al usar herramientas como scikit-learn de Python:

### 1. Descomponer las tablas
Descompón las tablas en:
- **Matriz A:** que contiene todas las características.
- **Vector b:** que contiene las etiquetas.

### 2. Generar la Matriz Ampliada B
Genera una matriz ampliada **B** añadiendo una primera columna de $1's$ y el resto con los valores de la matriz **A**, de modo que:
$$ B = [1|A] $$

### 3. Cálculo del Determinante
En los casos en que sea posible, calcula el determinante de las matrices **A** y **B**:
- Determinante de **A**: $ \text{det}(A) $
- Determinante de **B**: $ \text{det}(B) $

### 4. Cálculo del Rango
Calcula el rango de las matrices:
- **Rango de A**: $ \text{rank}(A) $
- **Rango de B**: $ \text{rank}(B) $

También, calcula el rango de las matrices ampliadas **[A|b]** y **[B|b]**:
$$ \text{rank}( [A|b] ) \quad \text{y} \quad \text{rank}( [B|b] ) $$

### 5. Clasificación de los Sistemas
Clasifica los sistemas:
- **Ax=b**
- **By=b**

según la clasificación de sistemas de ecuaciones lineales (determinado, indeterminado, o incompatible) basado en los rangos obtenidos.

### 6. Resolución de los Sistemas
Resuelve los sistemas utilizando:
- **Matriz inversa** si el sistema es determinado: $ x = A^{-1}b $
- **Pseudoinversa** en caso de ser un sistema indeterminado: $ x = A^{+}b $

Haz lo mismo para **B**:
$$ y = B^{-1}b \quad \text{o} \quad y = B^{+}b $$

### 7. Análisis de Estabilidad
Realiza un análisis de estabilidad de los sistemas a través de dilataciones y contracciones de las soluciones en factores del:
- $0.5\%$, $1\%$, $2\%$, $5\%$, y $10\%$.

Analiza los cambios porcentuales que se generan en las soluciones $b'$ perturbadas en relación con la $b$ real.

### 8. Intervalos de Confianza
Con el análisis anterior, establece una clase de intervalos de confianza en terminos de porcentaje para las soluciones obtenidas, considerando que:
- Las **dilataciones** podrían simular el redondeo o pérdida de precisión en los decimales de las soluciones.
- Las **contracciones** podrían simular errores numéricos pequeños o fluctuaciones en los datos originales.

### 9. Interpolantes
Las soluciones de los sistemas **Ax=b** y **By=b** pueden utilizarse para construir interpolantes:
- **Sin término independiente** para **Ax=b**.
- **Con término independiente** para **By=b**.

Construye dichos interpolantes.

### 10. Comparación de los Interpolantes
Analiza cuál de los interpolantes proporciona una solución más cercana a los valores de $b$, y argumenta si eso sería suficiente para justificar si es una mejor solución para el problema de interpolación.


In [2]:
# tabla (6x6)
import numpy as np
tabla_1 = np.array([[0.32047, 0.82356, 0.25645, 0.49580, 0.67355, 0.61427],
                  [0.29187, 0.44708, 0.19897, 0.89325, 0.73233, 0.89347],
                  [0.13883, 0.64831, 0.02541, 0.84798, 0.57868, 0.37958],
                  [0.89019, 0.36956, 0.23375, 0.45624, 0.18749, 0.25037],
                  [0.54278, 0.18745, 0.96885, 0.25942, 0.65492, 0.12485],
                  [0.76956, 0.06538, 0.49874, 0.82947, 0.86217, 0.78432]])


In [3]:
# tabla (6x6)
tabla_2 = np.array([[0.42533, 0.30128, 0.67274, 0.56891, 0.84945, 0.61348],
                  [0.89747, 0.25390, 0.18011, 0.45375, 0.61618, 0.23765],
                  [0.53472, 0.74909, 0.10292, 0.92582, 0.42937, 0.97256],
                  [0.82625, 0.66803, 0.48776, 0.61463, 0.06765, 0.81539],
                  [0.16523, 0.81656, 0.41254, 0.72114, 0.82603, 0.15945],
                  [0.72064, 0.37514, 0.57535, 0.25643, 0.53927, 0.69474]])


In [4]:
# tabla (8x7)
tabla_3 = np.array([[0.74898, 0.28122, 0.52920, 0.56900, 0.91599, 0.26114, 0.85767],
                  [0.87788, 0.57300, 0.21391, 0.18360, 0.27809, 0.47191, 0.52021],
                  [0.87446, 0.54117, 0.65085, 0.02731, 0.92548, 0.95857, 0.84126],
                  [0.44242, 0.31208, 0.45062, 0.48809, 0.24730, 0.08539, 0.49884],
                  [0.36721, 0.45338, 0.60793, 0.01837, 0.66224, 0.12615, 0.33194],
                  [0.54924, 0.69931, 0.05451, 0.81977, 0.56267, 0.36233, 0.99719],
                  [0.77000, 0.20419, 0.72319, 0.47703, 0.62884, 0.70215, 0.00228],
                  [0.59750, 0.39309, 0.90533, 0.88076, 0.34626, 0.56525, 0.59347]])


In [5]:
# tabla (8x7)
tabla_4 = np.array([[0.43217, 0.27185, 0.63925, 0.14753, 0.65845, 0.72451, 0.92756],
                  [0.85973, 0.55467, 0.10348, 0.38429, 0.97862, 0.30109, 0.36874],
                  [0.18459, 0.66988, 0.47842, 0.82746, 0.13367, 0.93471, 0.74512],
                  [0.04917, 0.76520, 0.56264, 0.05618, 0.31561, 0.90881, 0.09857],
                  [0.70551, 0.97730, 0.84481, 0.27559, 0.12154, 0.54392, 0.64783],
                  [0.96104, 0.86563, 0.05429, 0.34809, 0.25537, 0.21155, 0.28367],
                  [0.57384, 0.78641, 0.19932, 0.14379, 0.47252, 0.20055, 0.18792],
                  [0.31864, 0.96378, 0.48521, 0.11467, 0.89523, 0.69090, 0.45634]])

In [6]:
# tabla (6x7)
tabla_5 = np.array([[0.42074, 0.65412, 0.71950, 0.81775, 0.39471, 0.74543, 0.67315],
                  [0.12866, 0.89460, 0.56291, 0.21824, 0.99422, 0.40157, 0.58752],
                  [0.51278, 0.70214, 0.28451, 0.45349, 0.07861, 0.13209, 0.24194],
                  [0.89752, 0.67005, 0.46527, 0.84486, 0.87365, 0.26328, 0.45833],
                  [0.18930, 0.49567, 0.95384, 0.27422, 0.10112, 0.65198, 0.78461],
                  [0.36893, 0.76034, 0.01245, 0.21353, 0.07645, 0.84261, 0.03150]])


In [7]:
# tabla (8x7)
tabla_6 = np.array([[0.74898, 0.28122, 0.52920, 0.56900, 0.91599, 0.26114, 0.85767],
                  [0.87788, 0.57300, 0.21391, 0.18360, 0.27809, 0.47191, 0.52021],
                  [0.87446, 0.54117, 0.65085, 0.02731, 0.92548, 0.95857, 0.84126],
                  [0.44242, 0.31208, 0.45062, 0.48809, 0.24730, 0.08539, 0.49884],
                  [0.36721, 0.45338, 0.60793, 0.01837, 0.66224, 0.12615, 0.33194],
                  [0.54924, 0.69931, 0.05451, 0.81977, 0.56267, 0.36233, 0.99719],
                  [0.77000, 0.20419, 0.72319, 0.47703, 0.62884, 0.70215, 0.00228],
                  [0.59750, 0.39309, 0.90533, 0.88076, 0.34626, 0.56525, 0.59347]])


In [8]:
import numpy as np
from numpy.linalg import det, matrix_rank, inv, pinv

In [17]:
##Separar matriz A de vectores B

rows= tabla_2.shape[0]
columns = tabla_2.shape[1]

matriz_base_A= tabla_5[0:rows, 0:columns - 1] 
vector_b= tabla_5[0: rows, columns -1: columns ] 

print(matriz_base_A)


[[0.42074 0.65412 0.7195  0.81775 0.39471]
 [0.12866 0.8946  0.56291 0.21824 0.99422]
 [0.51278 0.70214 0.28451 0.45349 0.07861]
 [0.89752 0.67005 0.46527 0.84486 0.87365]
 [0.1893  0.49567 0.95384 0.27422 0.10112]
 [0.36893 0.76034 0.01245 0.21353 0.07645]]


In [18]:
### 2. Crear matriz (1|A)
rows = matriz_base_A.shape[0]
columns = matriz_base_A.shape[1]

columna_1s = np.ones((rows, 1))
matriz_B= np.zeros((matriz_base_A.shape[0] , matriz_base_A.shape[1] + 1))
matriz_B [0:rows, 1: columns +1 ] = matriz_base_A
matriz_B [0:rows, 0 :1  ] = columna_1s

print(matriz_B)

[[1.      0.42074 0.65412 0.7195  0.81775 0.39471]
 [1.      0.12866 0.8946  0.56291 0.21824 0.99422]
 [1.      0.51278 0.70214 0.28451 0.45349 0.07861]
 [1.      0.89752 0.67005 0.46527 0.84486 0.87365]
 [1.      0.1893  0.49567 0.95384 0.27422 0.10112]
 [1.      0.36893 0.76034 0.01245 0.21353 0.07645]]


In [19]:
### 3. Calculo del determinante A i B
if matriz_base_A.shape[0] == matriz_base_A.shape[1]: print(det(matriz_base_A))
else: print('Matrix_A not squared')

if matriz_B.shape[0] == matriz_B.shape[1]: print(det(matriz_B))
else: print('Matrix_B not squared')




Matrix_A not squared
0.015530180948421311


In [20]:
### 4. Calculo del rank
rank_A=matrix_rank(matriz_base_A)
rank_B= matrix_rank(matriz_B)

rank_Ab = matrix_rank(np.hstack((matriz_base_A, vector_b)))
rank_Bb = matrix_rank(np.hstack((matriz_B, vector_b)))



In [21]:
# 5. Clasifica los sistemas Ax= b y Bx = b

def classer_system(rank_matrix_1, rank_amplied_matrix_1, vector):

    if rank_matrix_1!=rank_amplied_matrix_1:
        print('Sistema incompatible')

    elif rank_matrix_1==rank_amplied_matrix_1!=vector.shape[0]:
        print('Sistema compatible indeterminado')

    elif rank_matrix_1==rank_amplied_matrix_1==vector.shape[0]: 
        print('Sistema compatible determinado')

    else: print('Algo fue mal, comprueba el input')

classer_system(rank_A, rank_Ab, vector_b)
classer_system(rank_B, rank_Bb, vector_b)

# I'd use a function here so it works with evert combination, alas it's not allowed
#print(rank_A, rank_Ab, vector_b.shape[0], '''Since, amplied matrix rank and base matrix are different it's a SI system \n''')

#print(rank_B, rank_Bb, vector_b.shape[0], '''Since, amplied matrix rank and base matrix are different it's a SI system''')

Sistema incompatible
Sistema compatible determinado


In [23]:
# 6. Solución de sistemas


# matriz_inversa = inv(matriz_base_A)
# solucion= matriz_inversa @ vector_b


matriz_inversa = inv(matriz_B)
x_base= matriz_inversa @ vector_b

solucion


array([[-0.13694395],
       [ 0.03930321],
       [ 0.77673323],
       [ 0.1191841 ],
       [ 0.10297286],
       [ 0.01085549]])

In [24]:
# 7. Analisis de estabilidad, analiza la diferencia entre b' y la b real %

perturbaciones = [0.005, 0.01, 0.05, 0.1]
matriz_inversa = inv(matriz_B)
matriz_temp = matriz_B.copy()

for perturbacion in perturbaciones:
    x_perturbada = x_base * perturbacion + x_base
    b_perturbada= matriz_temp.copy() @ x_perturbada

    diferencia = b_perturbada - vector_b
    norma = (diferencia.transpose() @ diferencia)**0.5
    norma_b = (vector_b.transpose() @ vector_b)**0.5

    print(f'Con la perturbacion de {perturbacion*100}%, obtenemos una diferencia de: \t {norma[0,0]*100/norma_b[0,0]}%')

    
    

Con la perturbacion de 0.5%, obtenemos una diferencia de: 	 0.4999999999997676%
Con la perturbacion de 1.0%, obtenemos una diferencia de: 	 0.9999999999998627%
Con la perturbacion de 5.0%, obtenemos una diferencia de: 	 4.99999999999975%
Con la perturbacion de 10.0%, obtenemos una diferencia de: 	 9.99999999999979%


In [ ]:
# 8.  Establece rangos de confianza
# Las soluciones del sistema soportan un 10% de error

In [28]:
# 9. Construye interpolantes para Ax= b y By= b

interpolante_B = lambda r : sum([r[i]*x_base[i] for i in range(len(r))])




In [32]:
RMSE_B =  (sum([(interpolante_B(matriz_B[i,:]) - vector_b[i])**2 for i in range(len(vector_b))])/len(vector_b))**0.5
RMSE_B

array([9.43417418e-16])